services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: pwebshop-sql
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Only_For_D3v!"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    restart: always

volumes:
  sql-data:
