services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pwebshop-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Development_s3rv3r!
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data:
